### ISSUE TITLE
描边颜色对不上

### ISSUE THREAD

**Issue by DaLooog** [Jin8868/TextOutline#1]
发现属性面板上调节的颜色和Scene下的颜色有偏差的

**Comment by Jin8868** [comment]
在工程的SampleScene下没复现，能否提供一下截图或者复现的最小工程。

**Comment by DaLooog** [comment]
Tuanjie引擎1.2.3。同一个色值，和unity默认的outline颜色不一致
![1731579439534](https://github.com/user-attachments/assets/f8eac581-0cf2-4f09-b018-3abd8d7f770a)

![1731579448688](https://github.com/user-attachments/assets/b91b749b-fd9d-4f25-b885-8e34a33e81db)

**Comment by Jin8868** [comment]
### 原因出在了项目的颜色空间设置中，你应该是使用线性空间了。如果项目没有使用到线性空间，直接改设置到gamma就ok了。如果使用到的话，我在shader中添加了gamma校正的开关，等我晚上回去更新。
![1731640134134](https://github.com/user-attachments/assets/04565d9c-a2ac-4458-b907-0969d7f23603)
![1731640144708](https://github.com/user-attachments/assets/efd430a4-0477-4bfb-92a9-12978e4823f4)
### **线性空间未加gamma校正，显示不正常**
![Snipaste_2024-11-15_11-14-22](https://github.com/user-attachments/assets/abfd5bef-fc49-4171-b89a-0090454ccc87)
### **线性空间添加gamma校正，显示正常，但因为颜色转换涉及浮点数精度，会有些许颜色偏差，但偏差不大可接受。**
![Snipaste_2024-11-15_11-14-44](https://github.com/user-attachments/assets/c16a5a07-b1f6-4779-954b-72c16e063b0f)

**Comment by Jin8868** [comment]
> 发现属性面板上调节的颜色和Scene下的颜色有偏差的

代码已经提交，更新按照Readme勾选材质选项即可。

**Comment by DaLooog** [comment]
完美解决，大佬大佬！
